package vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.Asiento;
import modelo.Autobus;
import modelo.Boleto;
import modelo.Conexion;
import modelo.Descuento;
import modelo.Pasajero;

public class VentanaDatosPasajero extends javax.swing.JFrame {    
    public VentanaDatosPasajero(Autobus autobus, Asiento asiento, Boleto boleto) {        
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAPP.png")).getImage());
        setLocationRelativeTo(null);        
        venderBoleto_btn.setEnabled(false);        
        cerrarSesion_btn1.setEnabled(false);
        consultarVentas_btn.setEnabled(false);
        
        String numero = String.valueOf(autobus.getNumeroAutobus());
        numeroAutobusTxt.setText(numero);
        setOrigenLabel.setText(autobus.getNombreOrigen());
        setDestinoLabel.setText(autobus.getNombreDestino());
        
        String precio = Double.toString(autobus.getPrecioViaje());
        setPrecioLabel.setText(precio); 
        
        setFechaLabel.setText(autobus.getFechaViaje());
        setHorarioLabel.setText(autobus.getHorarioViaje());
        setAsientoLabel.setText(asiento.obtenerAsientos());
        
        String precioAnterior = String.valueOf(boleto.getPrecioFinal());
        setPrecioAnterior.setText(precioAnterior);
        
        cargarDescuentos(descuentoCbox);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logoLabel1 = new javax.swing.JLabel();
        cerrarSesion_btn1 = new javax.swing.JToggleButton();
        venderBoleto_btn = new javax.swing.JToggleButton();
        consultarVentas_btn = new javax.swing.JToggleButton();
        origenLabel = new javax.swing.JLabel();
        destinoLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        setAsientoLabel = new javax.swing.JLabel();
        setFechaLabel = new javax.swing.JLabel();
        setPrecioLabel = new javax.swing.JLabel();
        setDestinoLabel = new javax.swing.JLabel();
        setOrigenLabel = new javax.swing.JLabel();
        regresarBtn1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOculta = new javax.swing.JTable();
        nombreLabel = new javax.swing.JLabel();
        continuarBtn1 = new javax.swing.JButton();
        setHorarioLabel = new javax.swing.JLabel();
        numeroAutobusTxt = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        asientoLabel1 = new javax.swing.JLabel();
        apellidoPaternoLabel = new javax.swing.JLabel();
        apellidoMaternoTxt = new javax.swing.JTextField();
        seleccionarDescuento = new javax.swing.JLabel();
        apellidoPaternoTxt = new javax.swing.JTextField();
        descuentoCbox = new javax.swing.JComboBox<>();
        ApellidoMaternoLabel1 = new javax.swing.JLabel();
        setPrecioAnterior = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");

        jPanel2.setBackground(new java.awt.Color(242, 235, 244));
        jPanel2.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logoLabel1.setText("LOGO");
        jPanel2.add(logoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        cerrarSesion_btn1.setBackground(new java.awt.Color(236, 145, 117));
        cerrarSesion_btn1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        cerrarSesion_btn1.setText("CERRAR SESIÓN");
        cerrarSesion_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesion_btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(cerrarSesion_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 80));

        venderBoleto_btn.setBackground(new java.awt.Color(236, 145, 117));
        venderBoleto_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        venderBoleto_btn.setText("VENDER BOLETO");
        venderBoleto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderBoleto_btnActionPerformed(evt);
            }
        });
        jPanel2.add(venderBoleto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 440, 80));

        consultarVentas_btn.setBackground(new java.awt.Color(236, 145, 117));
        consultarVentas_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        consultarVentas_btn.setText("CONSULTAR VENTAS");
        jPanel2.add(consultarVentas_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 420, 80));

        origenLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        origenLabel.setText("ORIGEN:");
        jPanel2.add(origenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        destinoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        destinoLabel.setText("DESTINO:");
        jPanel2.add(destinoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        precioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        precioLabel.setText("PRECIO:");
        jPanel2.add(precioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        fechaLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        fechaLabel.setText("FECHA DE SALIDA:");
        jPanel2.add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        horarioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        horarioLabel.setText("HORARIO:");
        jPanel2.add(horarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        setAsientoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setAsientoLabel.setText("Ttx");
        jPanel2.add(setAsientoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        setFechaLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setFechaLabel.setText("Ttx");
        jPanel2.add(setFechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        setPrecioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setPrecioLabel.setText("Ttx");
        jPanel2.add(setPrecioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));

        setDestinoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setDestinoLabel.setText("Ttx");
        jPanel2.add(setDestinoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        setOrigenLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setOrigenLabel.setText("Ttx");
        jPanel2.add(setOrigenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        regresarBtn1.setBackground(new java.awt.Color(236, 145, 117));
        regresarBtn1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        regresarBtn1.setText("REGRESAR");
        regresarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(regresarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, -1, -1));

        tablaOculta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaOculta.setEnabled(false);
        tablaOculta.setFocusable(false);
        jScrollPane1.setViewportView(tablaOculta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 20, 20));

        nombreLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        nombreLabel.setText("NOMBRE (S):");
        jPanel2.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        continuarBtn1.setBackground(new java.awt.Color(236, 145, 117));
        continuarBtn1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        continuarBtn1.setText("CONTINUAR");
        continuarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(continuarBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, -1, -1));

        setHorarioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setHorarioLabel.setText("Ttx");
        jPanel2.add(setHorarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));

        numeroAutobusTxt.setText("jLabel7");
        jPanel2.add(numeroAutobusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 130, -1, -1));

        nombreTxt.setBackground(new java.awt.Color(236, 145, 117));
        nombreTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel2.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 240, 40));

        asientoLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        asientoLabel1.setText("ASIENTO (S):");
        jPanel2.add(asientoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        apellidoPaternoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        apellidoPaternoLabel.setText("APELLIDO MATERNO:");
        jPanel2.add(apellidoPaternoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, -1, -1));

        apellidoMaternoTxt.setBackground(new java.awt.Color(236, 145, 117));
        apellidoMaternoTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel2.add(apellidoMaternoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 240, 40));

        seleccionarDescuento.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        seleccionarDescuento.setText("DESCUENTO:");
        jPanel2.add(seleccionarDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, -1, -1));

        apellidoPaternoTxt.setBackground(new java.awt.Color(236, 145, 117));
        apellidoPaternoTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel2.add(apellidoPaternoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 240, 40));

        descuentoCbox.setBackground(new java.awt.Color(236, 145, 117));
        descuentoCbox.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        descuentoCbox.setToolTipText("");
        jPanel2.add(descuentoCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 240, 40));

        ApellidoMaternoLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ApellidoMaternoLabel1.setText("APELLIDO PATERNO:");
        jPanel2.add(ApellidoMaternoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));

        setPrecioAnterior.setText("0.0");
        jPanel2.add(setPrecioAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarBtn1ActionPerformed
                       
        Boleto boleto = new Boleto();
        Pasajero pasajero = new Pasajero();
        Descuento descuento = new Descuento();
        Autobus autobus = new Autobus();
        Asiento asiento = new Asiento();
        
        if(nombreTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el nombre del pasajero", "Datos incompletos", JOptionPane.WARNING_MESSAGE);
        }else if(apellidoMaternoTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el apellido paterno del pasajero", "Datos incompletos", JOptionPane.WARNING_MESSAGE);
        }else if(apellidoPaternoTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el apellido materno del pasajero", "Datos incompletos", JOptionPane.WARNING_MESSAGE);
        }else if(descuentoCbox.getSelectedItem().equals("Seleccione un tipo de boleto")){
            JOptionPane.showMessageDialog(this, "Debe elegir un descuento", "Datos incompletos", JOptionPane.WARNING_MESSAGE);            
        }else{
                        
            //origen        
            autobus.setNombreOrigen(setOrigenLabel.getText());  
            //destino        
            autobus.setNombreDestino(setDestinoLabel.getText());
            //Precio viaje
            double precio = Double.parseDouble(setPrecioLabel.getText());
            autobus.setPrecioViaje(precio);
            //fecha
            autobus.setFechaViaje(setFechaLabel.getText());
            //horario        
            autobus.setHorarioViaje(setHorarioLabel.getText());  
            //Asiento
            int asientoInt = Integer.parseInt(setAsientoLabel.getText());
            asiento.setNumeroAsiento(asientoInt);                                              
            asiento.add(asiento);            
            
            int numeroAutobus = Integer.parseInt(numeroAutobusTxt.getText());
            autobus.setNumeroAutobus(numeroAutobus);  
            String tipoDescuento = descuentoCbox.getSelectedItem().toString();
            descuento.setTipoDescuento(tipoDescuento);
            boleto.seleccionarDescuento(descuento);
            pasajero.setNombrePasajero(nombreTxt.getText());
            pasajero.setApellidoPaternoPasajero(apellidoPaternoTxt.getText());
            pasajero.setApellidoMaternoPasajero(apellidoMaternoTxt.getText());                                      
            
            pasajero.add(pasajero);
                       
            Double precioAnterior = Double.parseDouble(setPrecioAnterior.getText());
            boleto.setPrecioFinal(precioAnterior);
            
            if(precioAnterior != 0.0){
                VentanaNuevoCobro nuevoCobro = new VentanaNuevoCobro(pasajero, boleto, autobus, descuento, asiento);
                nuevoCobro.setVisible(true);
                this.setVisible(false);
            }else{
                VentanaCobrar cobrar = new VentanaCobrar(pasajero, boleto, autobus, descuento, asiento);
                cobrar.setVisible(true);
                this.setVisible(false); 
            }
            
        }                
    }//GEN-LAST:event_continuarBtn1ActionPerformed

    private void regresarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtn1ActionPerformed
        Autobus autobus = new Autobus();
        Boleto boleto = new Boleto();
        
        int numero = Integer.parseInt(numeroAutobusTxt.getText());
        autobus.setNumeroAutobus(numero);        
        autobus.setNombreOrigen(setOrigenLabel.getText()); 
        autobus.setNombreDestino(setDestinoLabel.getText());
        double precioD = Double.parseDouble(setPrecioLabel.getText());        
        autobus.setPrecioViaje(precioD);
        autobus.setHorarioViaje(setHorarioLabel.getText());               
        autobus.setFechaViaje(setFechaLabel.getText());
        
        VentanaAsiento ventanaAsiento = new VentanaAsiento(autobus, boleto);
        ventanaAsiento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarBtn1ActionPerformed

    private void venderBoleto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderBoleto_btnActionPerformed

    }//GEN-LAST:event_venderBoleto_btnActionPerformed

    private void cerrarSesion_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesion_btn1ActionPerformed

    }//GEN-LAST:event_cerrarSesion_btn1ActionPerformed

    public boolean cargarDescuentos(JComboBox comboBox){
                     
        Conexion conn = new Conexion();
        Connection reg = conn.conectar();  
        Connection con = reg; 
         
        PreparedStatement ps = null;
        ResultSet rs = null;                       
        
        String sql = "SELECT tipoDescuento FROM descuento";
        
        try{
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            comboBox.addItem("Seleccione un tipo de boleto");
            
            while(rs.next()){
                comboBox.addItem(rs.getString("tipoDescuento"));
            }
            return true;
        }catch(Exception e){
            System.out.println("Error en la consulta: " + e);
            return false;
        }      
    }  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosPasajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new VentanaDatosPasajero().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoMaternoLabel1;
    private javax.swing.JTextField apellidoMaternoTxt;
    private javax.swing.JLabel apellidoPaternoLabel;
    private javax.swing.JTextField apellidoPaternoTxt;
    private javax.swing.JLabel asientoLabel1;
    private javax.swing.JToggleButton cerrarSesion_btn1;
    private javax.swing.JToggleButton consultarVentas_btn;
    private javax.swing.JButton continuarBtn1;
    private javax.swing.JComboBox<String> descuentoCbox;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel numeroAutobusTxt;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JButton regresarBtn1;
    private javax.swing.JLabel seleccionarDescuento;
    private javax.swing.JLabel setAsientoLabel;
    private javax.swing.JLabel setDestinoLabel;
    private javax.swing.JLabel setFechaLabel;
    private javax.swing.JLabel setHorarioLabel;
    private javax.swing.JLabel setOrigenLabel;
    private javax.swing.JLabel setPrecioAnterior;
    private javax.swing.JLabel setPrecioLabel;
    private javax.swing.JTable tablaOculta;
    private javax.swing.JToggleButton venderBoleto_btn;
    // End of variables declaration//GEN-END:variables
}
