package vistas;

import javax.swing.ImageIcon;
import modelo.Acceso;

public class VentanaAdministrador extends javax.swing.JFrame {

    public VentanaAdministrador() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAPP.png")).getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        consultarVentas_btn2 = new javax.swing.JToggleButton();
        cerrarSesion_btn2 = new javax.swing.JToggleButton();
        altaBtn = new javax.swing.JToggleButton();
        agregarDescuentoBtn = new javax.swing.JButton();
        agregarAutobusBtn = new javax.swing.JButton();
        modifiacarAutobusBtn = new javax.swing.JButton();
        modificarDescuentoBtn = new javax.swing.JButton();
        eliminarAutobusBtn = new javax.swing.JButton();
        eliminarDescuentoBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");

        jPanel3.setBackground(new java.awt.Color(242, 235, 244));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("LOGO");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        consultarVentas_btn2.setBackground(new java.awt.Color(236, 145, 117));
        consultarVentas_btn2.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        consultarVentas_btn2.setText("CONSULTAR VENTAS");
        consultarVentas_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVentas_btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(consultarVentas_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 420, 80));

        cerrarSesion_btn2.setBackground(new java.awt.Color(236, 145, 117));
        cerrarSesion_btn2.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        cerrarSesion_btn2.setText("CERRAR SESIÓN");
        cerrarSesion_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesion_btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(cerrarSesion_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 420, 80));

        altaBtn.setBackground(new java.awt.Color(236, 145, 117));
        altaBtn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        altaBtn.setText("DAR DE ALTA A PERSONAL");
        altaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaBtnActionPerformed(evt);
            }
        });
        jPanel3.add(altaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 440, 80));

        agregarDescuentoBtn.setBackground(new java.awt.Color(236, 145, 117));
        agregarDescuentoBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        agregarDescuentoBtn.setText("AGREGAR DESCUENTO");
        agregarDescuentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDescuentoBtnActionPerformed(evt);
            }
        });
        jPanel3.add(agregarDescuentoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 190, -1));

        agregarAutobusBtn.setBackground(new java.awt.Color(236, 145, 117));
        agregarAutobusBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        agregarAutobusBtn.setText("AGREGAR AUTOBUS");
        agregarAutobusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAutobusBtnActionPerformed(evt);
            }
        });
        jPanel3.add(agregarAutobusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 190, -1));

        modifiacarAutobusBtn.setBackground(new java.awt.Color(236, 145, 117));
        modifiacarAutobusBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        modifiacarAutobusBtn.setText("MODIFICAR AUTOBUS");
        modifiacarAutobusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifiacarAutobusBtnActionPerformed(evt);
            }
        });
        jPanel3.add(modifiacarAutobusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 200, -1));

        modificarDescuentoBtn.setBackground(new java.awt.Color(236, 145, 117));
        modificarDescuentoBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        modificarDescuentoBtn.setText("MODIFICAR DESCUENTO");
        modificarDescuentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarDescuentoBtnActionPerformed(evt);
            }
        });
        jPanel3.add(modificarDescuentoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 200, -1));

        eliminarAutobusBtn.setBackground(new java.awt.Color(236, 145, 117));
        eliminarAutobusBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        eliminarAutobusBtn.setText("ELIMINAR AUTOBUS");
        eliminarAutobusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAutobusBtnActionPerformed(evt);
            }
        });
        jPanel3.add(eliminarAutobusBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, 190, -1));

        eliminarDescuentoBtn.setBackground(new java.awt.Color(236, 145, 117));
        eliminarDescuentoBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        eliminarDescuentoBtn.setText("ELIMINAR DESCUENTO");
        eliminarDescuentoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDescuentoBtnActionPerformed(evt);
            }
        });
        jPanel3.add(eliminarDescuentoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yram\\Documents\\NetBeansProjects\\SistemaVentaBoletos\\src\\imagenes\\eliminar.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yram\\Documents\\NetBeansProjects\\SistemaVentaBoletos\\src\\imagenes\\Agregar.png")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yram\\Documents\\NetBeansProjects\\SistemaVentaBoletos\\src\\imagenes\\Editar.png")); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesion_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesion_btn2ActionPerformed
        Acceso acceso = new Acceso();
        if(acceso.cerrarSesion()){
            VentanaLogin ventanaLogin = new VentanaLogin();
            ventanaLogin.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cerrarSesion_btn2ActionPerformed

    private void altaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBtnActionPerformed
        VentanaAltaPersonal alta = new VentanaAltaPersonal();
        alta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_altaBtnActionPerformed

    private void agregarDescuentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDescuentoBtnActionPerformed
        VentanaAgregarDescuento agregarDescuento = new VentanaAgregarDescuento();
        agregarDescuento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agregarDescuentoBtnActionPerformed

    private void agregarAutobusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAutobusBtnActionPerformed
        VentanaAgregarAutobus agregarAutobus = new VentanaAgregarAutobus();
        agregarAutobus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agregarAutobusBtnActionPerformed

    private void modifiacarAutobusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifiacarAutobusBtnActionPerformed
        VentanaModificarAutobus modificarAutobus = new VentanaModificarAutobus();
        modificarAutobus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifiacarAutobusBtnActionPerformed

    private void modificarDescuentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarDescuentoBtnActionPerformed
        VentanaModificarDescuento modificarDescuento = new VentanaModificarDescuento();
        modificarDescuento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modificarDescuentoBtnActionPerformed

    private void eliminarAutobusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAutobusBtnActionPerformed
        VentanaEliminarAutobus eliminarAutobus = new VentanaEliminarAutobus();
        eliminarAutobus.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminarAutobusBtnActionPerformed

    private void eliminarDescuentoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDescuentoBtnActionPerformed
        VentanaEliminarDescuento eliminarDescuento = new VentanaEliminarDescuento();
        eliminarDescuento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_eliminarDescuentoBtnActionPerformed

    private void consultarVentas_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVentas_btn2ActionPerformed
        VentanaConsultarVentasAdministrador consultarVentas = new VentanaConsultarVentasAdministrador();
        consultarVentas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultarVentas_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAutobusBtn;
    private javax.swing.JButton agregarDescuentoBtn;
    private javax.swing.JToggleButton altaBtn;
    private javax.swing.JToggleButton cerrarSesion_btn2;
    private javax.swing.JToggleButton consultarVentas_btn2;
    private javax.swing.JButton eliminarAutobusBtn;
    private javax.swing.JButton eliminarDescuentoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton modifiacarAutobusBtn;
    private javax.swing.JButton modificarDescuentoBtn;
    // End of variables declaration//GEN-END:variables
}
