package vistas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Acceso;
import modelo.Administrador;
import modelo.PersonalVentas;

public class VentanaAltaPersonal extends javax.swing.JFrame {

    public VentanaAltaPersonal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAPP.png")).getImage());
        setLocationRelativeTo(null);
        altaBtn.setEnabled(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        consultarVentasBtn = new javax.swing.JToggleButton();
        cerrarSesionBtn = new javax.swing.JToggleButton();
        altaBtn = new javax.swing.JToggleButton();
        salirBtn = new javax.swing.JButton();
        darAltaBtn = new javax.swing.JButton();
        idAccesoTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        apellidoPaternoTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        apellidoMaternoTxt = new javax.swing.JTextField();
        curpTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");

        jPanel3.setBackground(new java.awt.Color(242, 235, 244));
        jPanel3.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("LOGO");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        consultarVentasBtn.setBackground(new java.awt.Color(236, 145, 117));
        consultarVentasBtn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        consultarVentasBtn.setText("CONSULTAR VENTAS");
        consultarVentasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVentasBtnActionPerformed(evt);
            }
        });
        jPanel3.add(consultarVentasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 420, 80));

        cerrarSesionBtn.setBackground(new java.awt.Color(236, 145, 117));
        cerrarSesionBtn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        cerrarSesionBtn.setText("CERRAR SESIÓN");
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });
        jPanel3.add(cerrarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 420, 80));

        altaBtn.setBackground(new java.awt.Color(236, 145, 117));
        altaBtn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        altaBtn.setText("DAR DE ALTA A PERSONAL");
        altaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaBtnActionPerformed(evt);
            }
        });
        jPanel3.add(altaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 440, 80));

        salirBtn.setBackground(new java.awt.Color(236, 145, 117));
        salirBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        salirBtn.setText("SALIR");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        jPanel3.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 660, 140, -1));

        darAltaBtn.setBackground(new java.awt.Color(236, 145, 117));
        darAltaBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        darAltaBtn.setText("DAR DE ALTA");
        darAltaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darAltaBtnActionPerformed(evt);
            }
        });
        jPanel3.add(darAltaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 660, 200, -1));

        idAccesoTxt.setBackground(new java.awt.Color(236, 145, 117));
        idAccesoTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        idAccesoTxt.setToolTipText("ID Acceso");
        jPanel3.add(idAccesoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 300, 60));

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel2.setText("ID ACCESO:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel3.setText("NOMBRE (S):");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, -1));

        nombreTxt.setBackground(new java.awt.Color(236, 145, 117));
        nombreTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        nombreTxt.setToolTipText("ID Acceso");
        jPanel3.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 300, 60));

        apellidoPaternoTxt.setBackground(new java.awt.Color(236, 145, 117));
        apellidoPaternoTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        apellidoPaternoTxt.setToolTipText("ID Acceso");
        jPanel3.add(apellidoPaternoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 300, 60));

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel4.setText("APELLIDO PATERNO:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel5.setText("APELLIDO MATERNO:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, -1, -1));

        apellidoMaternoTxt.setBackground(new java.awt.Color(236, 145, 117));
        apellidoMaternoTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        apellidoMaternoTxt.setToolTipText("ID Acceso");
        jPanel3.add(apellidoMaternoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 300, 60));

        curpTxt.setBackground(new java.awt.Color(236, 145, 117));
        curpTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        curpTxt.setToolTipText("ID Acceso");
        jPanel3.add(curpTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 300, 60));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel7.setText("CURP:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yram\\Documents\\NetBeansProjects\\SistemaVentaBoletos\\src\\imagenes\\Inicia_sesion.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        Acceso acceso = new Acceso();
        if(acceso.cerrarSesion()){
            VentanaLogin ventanaLogin = new VentanaLogin();
            ventanaLogin.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cerrarSesionBtnActionPerformed

    private void altaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBtnActionPerformed

    }//GEN-LAST:event_altaBtnActionPerformed

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        VentanaAdministrador menu = new VentanaAdministrador();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void darAltaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darAltaBtnActionPerformed
        Administrador alta = new Administrador();
        PersonalVentas personal = new PersonalVentas();
        if(idAccesoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debes ingresar el ID del personal", "Campo vacío", JOptionPane.WARNING_MESSAGE);   
        }else if(nombreTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debes ingresar el nombre del personal", "Campo vacío", JOptionPane.WARNING_MESSAGE);                
        }else if(apellidoPaternoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debes ingresar el apellido paterno del personal", "Campo vacío", JOptionPane.WARNING_MESSAGE);                    
        }else if(apellidoMaternoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debes ingresar el apellido materno del personal", "Campo vacío", JOptionPane.WARNING_MESSAGE);                        
        }else if(curpTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debes ingresar la CURP del personal", "Campo vacío", JOptionPane.WARNING_MESSAGE);                            
        }else{
            personal.setCodigoPersonalVentas(idAccesoTxt.getText());
            personal.setNombrePersonalVentas(nombreTxt.getText());
            personal.setApellidoPaternoPersonalVentas(apellidoPaternoTxt.getText());
            personal.setApellidoMaternoPersonalVentas(apellidoMaternoTxt.getText());
            personal.setCurpPersonalVentas(curpTxt.getText());
            if(alta.altaPersonal(personal)){
                idAccesoTxt.setText("");
                nombreTxt.setText("");
                apellidoPaternoTxt.setText("");
                apellidoMaternoTxt.setText("");
                curpTxt.setText("");
                JOptionPane.showMessageDialog(this, "El personal ha sido dado de alta exitosamente", "Alta exitosa", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Hubo un error al dar de alta al personal", "Error de datos", JOptionPane.ERROR_MESSAGE);
            }
        }               
    }//GEN-LAST:event_darAltaBtnActionPerformed

    private void consultarVentasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVentasBtnActionPerformed
        VentanaConsultarVentasAdministrador consultarVentas = new VentanaConsultarVentasAdministrador();
        consultarVentas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultarVentasBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAltaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAltaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAltaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAltaPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAltaPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton altaBtn;
    private javax.swing.JTextField apellidoMaternoTxt;
    private javax.swing.JTextField apellidoPaternoTxt;
    private javax.swing.JToggleButton cerrarSesionBtn;
    private javax.swing.JToggleButton consultarVentasBtn;
    private javax.swing.JTextField curpTxt;
    private javax.swing.JButton darAltaBtn;
    private javax.swing.JTextField idAccesoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JButton salirBtn;
    // End of variables declaration//GEN-END:variables
}
