 package vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Acceso;
import modelo.Asiento;
import modelo.Autobus;
import modelo.Boleto;
import modelo.Conexion;
import modelo.Descuento;
import modelo.Pasajero;

public class VentanaCancelarBoleto extends javax.swing.JFrame {

    public VentanaCancelarBoleto() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAPP.png")).getImage());
        setLocationRelativeTo(null);
        venderBoleto_btn.setEnabled(false);        
        cerrarSesion_btn.setEnabled(false);
        consultarVentas_btn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        consultarVentas_btn = new javax.swing.JToggleButton();
        cerrarSesion_btn = new javax.swing.JToggleButton();
        venderBoleto_btn = new javax.swing.JToggleButton();
        idBoletoLabel = new javax.swing.JLabel();
        idBoletoTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        regresarBtn = new javax.swing.JButton();
        datosBoletoLabel = new javax.swing.JLabel();
        apellidoPaternoLabel = new javax.swing.JLabel();
        apellidoMaternoLabel = new javax.swing.JLabel();
        nombrePasajeroLabel = new javax.swing.JLabel();
        setNombrePasajero = new javax.swing.JLabel();
        setApellidoMaterno = new javax.swing.JLabel();
        setApellidoPaterno = new javax.swing.JLabel();
        datosPasajeroLabel = new javax.swing.JLabel();
        destinoLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        origenLabel = new javax.swing.JLabel();
        setOrigen = new javax.swing.JLabel();
        setFecha = new javax.swing.JLabel();
        setDestino = new javax.swing.JLabel();
        horaLabel = new javax.swing.JLabel();
        setHora = new javax.swing.JLabel();
        buscarBoletoBtn1 = new javax.swing.JButton();
        continuarBtn = new javax.swing.JButton();
        setNumeroAutobus = new javax.swing.JLabel();
        setNumeroBoleto = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        setPrecio = new javax.swing.JLabel();
        setAsiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");

        jPanel1.setBackground(new java.awt.Color(242, 235, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("LOGO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        consultarVentas_btn.setBackground(new java.awt.Color(236, 145, 117));
        consultarVentas_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        consultarVentas_btn.setText("CONSULTAR VENTAS");
        jPanel1.add(consultarVentas_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 420, 80));

        cerrarSesion_btn.setBackground(new java.awt.Color(236, 145, 117));
        cerrarSesion_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        cerrarSesion_btn.setText("CERRAR SESIÓN");
        cerrarSesion_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesion_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cerrarSesion_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 80));

        venderBoleto_btn.setBackground(new java.awt.Color(236, 145, 117));
        venderBoleto_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        venderBoleto_btn.setText("VENDER BOLETO");
        venderBoleto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderBoleto_btnActionPerformed(evt);
            }
        });
        jPanel1.add(venderBoleto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 440, 80));

        idBoletoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        idBoletoLabel.setText("NÚMERO DE BOLETO:");
        jPanel1.add(idBoletoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        idBoletoTxt.setBackground(new java.awt.Color(236, 145, 117));
        idBoletoTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel1.add(idBoletoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 260, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Boletos.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        regresarBtn.setBackground(new java.awt.Color(236, 145, 117));
        regresarBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        regresarBtn.setText("REGRESAR");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 660, 130, 40));

        datosBoletoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        datosBoletoLabel.setText("DATOS DEL BOLETO:");
        jPanel1.add(datosBoletoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, -1, -1));

        apellidoPaternoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        apellidoPaternoLabel.setText("APELLIDO PATERNO:");
        jPanel1.add(apellidoPaternoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        apellidoMaternoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        apellidoMaternoLabel.setText("APELLIDO MATERNO:");
        jPanel1.add(apellidoMaternoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        nombrePasajeroLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        nombrePasajeroLabel.setText("NOMBRE:");
        jPanel1.add(nombrePasajeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        setNombrePasajero.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setNombrePasajero.setText("------------------------");
        jPanel1.add(setNombrePasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, -1, -1));

        setApellidoMaterno.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setApellidoMaterno.setText("------------------------");
        jPanel1.add(setApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        setApellidoPaterno.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setApellidoPaterno.setText("------------------------");
        jPanel1.add(setApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, -1));

        datosPasajeroLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        datosPasajeroLabel.setText("DATOS DEL PASAJERO:");
        jPanel1.add(datosPasajeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        destinoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        destinoLabel.setText("DESTINO:");
        jPanel1.add(destinoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, -1, -1));

        fechaLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        fechaLabel.setText("FECHA:");
        jPanel1.add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, -1, -1));

        origenLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        origenLabel.setText("ORIGEN:");
        jPanel1.add(origenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, -1));

        setOrigen.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setOrigen.setText("------------------------");
        jPanel1.add(setOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, -1, -1));

        setFecha.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setFecha.setText("------------------------");
        jPanel1.add(setFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, -1, -1));

        setDestino.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setDestino.setText("------------------------");
        jPanel1.add(setDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, -1, -1));

        horaLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        horaLabel.setText("HORA:");
        jPanel1.add(horaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 640, -1, -1));

        setHora.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setHora.setText("------------------------");
        jPanel1.add(setHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, -1, -1));

        buscarBoletoBtn1.setBackground(new java.awt.Color(236, 145, 117));
        buscarBoletoBtn1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        buscarBoletoBtn1.setText("BUSCAR");
        buscarBoletoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBoletoBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(buscarBoletoBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 130, 40));

        continuarBtn.setBackground(new java.awt.Color(236, 145, 117));
        continuarBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        continuarBtn.setText("CONTINUAR");
        continuarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(continuarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 610, 180, 40));

        setNumeroAutobus.setText("jLabel1");
        jPanel1.add(setNumeroAutobus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 90, -1, -1));

        setNumeroBoleto.setText("jLabel1");
        jPanel1.add(setNumeroBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 90, 30, -1));

        precioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        precioLabel.setText("PRECIO:");
        jPanel1.add(precioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 680, -1, -1));

        setPrecio.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setPrecio.setText("------------------------");
        jPanel1.add(setPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, -1, -1));

        setAsiento.setText("jLabel1");
        jPanel1.add(setAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesion_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesion_btnActionPerformed
        Acceso acceso = new Acceso();
        if(acceso.cerrarSesion()){
            VentanaLogin ventanaLogin = new VentanaLogin();
            ventanaLogin.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_cerrarSesion_btnActionPerformed

    private void venderBoleto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderBoleto_btnActionPerformed

    }//GEN-LAST:event_venderBoleto_btnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        VentanaVenderBoletos regresar = new VentanaVenderBoletos();
        regresar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void buscarBoletoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBoletoBtn1ActionPerformed
        Boleto boleto = new Boleto();        
        Autobus autobus = new Autobus();
        Descuento descuento = new Descuento();
        Pasajero pasajero = new Pasajero();
        Asiento asiento = new Asiento();
        
        if(idBoletoTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero de boleto", "Campo vacío", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                int codigoBoleto = Integer.parseInt(idBoletoTxt.getText());
                boleto.setCodigoBoleto(codigoBoleto);
                if(buscarBoleto(boleto)){
                    int numeroAutobus = Integer.parseInt(setNumeroAutobus.getText());
                    autobus.setNumeroAutobus(numeroAutobus);
                    if(buscarAutobus(autobus)){
                        JOptionPane.showMessageDialog(this, "El boleto ha sido encontrado con éxito", "Boleto encontrado", JOptionPane.INFORMATION_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "No se encontró el boleto ingresado o ya fué cancelado", "Operación no exitosa", JOptionPane.ERROR_MESSAGE);
                }  
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "El valor ingresado debe ser numero entero", "Operación no exitosa", JOptionPane.ERROR_MESSAGE);
            }    
        }
    }//GEN-LAST:event_buscarBoletoBtn1ActionPerformed

    private void continuarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarBtnActionPerformed
        Boleto boleto = new Boleto();        
        Asiento asiento = new Asiento();
        int codigoBoleto = Integer.parseInt(setNumeroBoleto.getText());        
        boleto.setCodigoBoleto(codigoBoleto);
        Double precioFinal = Double.parseDouble(setPrecio.getText());
        boleto.setPrecioFinal(precioFinal);
        if(boleto.cancelarBolteto(boleto)){
            int numeroAsiento = Integer.parseInt(setAsiento.getText());
            asiento.setNumeroAsiento(numeroAsiento);
            int numeroAutobus = Integer.parseInt(setNumeroAutobus.getText());
            asiento.setNumeroAutobus(numeroAutobus);
            if(asiento.cancelarAsiento(asiento)){
                VentanaCancelacionExitosa exito = new VentanaCancelacionExitosa(boleto);
                exito.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo cancelar el boleto", "Operación sin éxito", JOptionPane.ERROR_MESSAGE);
            }            
        }else{
            JOptionPane.showMessageDialog(this, "No se pudo cancelar el boleto", "Operación sin éxito", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_continuarBtnActionPerformed

    public boolean buscarBoleto(Boleto boleto){
        Conexion conn = new Conexion();
        Connection reg = conn.conectar();  
        Connection con = reg; 
         
        PreparedStatement ps = null;
        ResultSet rs = null;                          
        
        String sql = "SELECT * FROM boleto WHERE codigoBoleto = '" + boleto.getCodigoBoleto() + "' AND estado = 'Vendido'";
        
        try{
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){                
                setNumeroBoleto.setText(rs.getString(1));
                setNumeroAutobus.setText(rs.getString(3));                                                         
                setNombrePasajero.setText(rs.getString(5));
                setApellidoPaterno.setText(rs.getString(6));    
                setApellidoMaterno.setText(rs.getString(7));
                setAsiento.setText(rs.getString(8));
                setPrecio.setText(rs.getString(9));    
                return true;
            }            
            return false;
        }catch(Exception e){
            System.out.println("Error en la consulta: " + e);
            return false;
        }      
    }  
    
    public boolean buscarAutobus(Autobus autobus){               
        Conexion conn = new Conexion();
        Connection reg = conn.conectar();  
        Connection con = reg; 
         
        PreparedStatement ps = null;
        ResultSet rs = null;          
        
        //String []datos = new String[9];
        
        String sql = "SELECT * FROM autobus WHERE numeroAutobus = '" + autobus.getNumeroAutobus() + "'";
        
        try{
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            while(rs.next()){
               rs.getString(1);                              
               setOrigen.setText(rs.getString(2));
               setDestino.setText(rs.getString(3));               
               setFecha.setText(rs.getString(5));
               setHora.setText(rs.getString(6));                
            }            
            return true;
        }catch(Exception e){
            System.out.println("Error en la consulta: " + e);
            return false;
        }      
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCancelarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCancelarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCancelarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCancelarBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCancelarBoleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoMaternoLabel;
    private javax.swing.JLabel apellidoPaternoLabel;
    private javax.swing.JButton buscarBoletoBtn1;
    private javax.swing.JToggleButton cerrarSesion_btn;
    private javax.swing.JToggleButton consultarVentas_btn;
    private javax.swing.JButton continuarBtn;
    private javax.swing.JLabel datosBoletoLabel;
    private javax.swing.JLabel datosPasajeroLabel;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel horaLabel;
    private javax.swing.JLabel idBoletoLabel;
    private javax.swing.JTextField idBoletoTxt;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombrePasajeroLabel;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JLabel setApellidoMaterno;
    private javax.swing.JLabel setApellidoPaterno;
    private javax.swing.JLabel setAsiento;
    private javax.swing.JLabel setDestino;
    private javax.swing.JLabel setFecha;
    private javax.swing.JLabel setHora;
    private javax.swing.JLabel setNombrePasajero;
    private javax.swing.JLabel setNumeroAutobus;
    private javax.swing.JLabel setNumeroBoleto;
    private javax.swing.JLabel setOrigen;
    private javax.swing.JLabel setPrecio;
    private javax.swing.JToggleButton venderBoleto_btn;
    // End of variables declaration//GEN-END:variables
}
