package vistas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Acceso;

public class VentanaLogin extends javax.swing.JFrame {
    
    public VentanaLogin() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAPP.png")).getImage());
        setLocationRelativeTo(null);
        venderBoleto_btn.setEnabled(false);
        consultarVentas_btn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        consultarVentas_btn = new javax.swing.JToggleButton();
        iniciarSesion_Label = new javax.swing.JToggleButton();
        venderBoleto_btn = new javax.swing.JToggleButton();
        idAccesoTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        registrarseBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        contraseñaTxt = new javax.swing.JPasswordField();
        iniciarSesionBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cambiarContraseñaBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");

        jPanel1.setBackground(new java.awt.Color(242, 235, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("LOGO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        consultarVentas_btn.setBackground(new java.awt.Color(236, 145, 117));
        consultarVentas_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        consultarVentas_btn.setText("CONSULTAR VENTAS");
        jPanel1.add(consultarVentas_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 420, 80));

        iniciarSesion_Label.setBackground(new java.awt.Color(236, 145, 117));
        iniciarSesion_Label.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        iniciarSesion_Label.setText("INICIAR SESIÓN");
        jPanel1.add(iniciarSesion_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 80));

        venderBoleto_btn.setBackground(new java.awt.Color(236, 145, 117));
        venderBoleto_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        venderBoleto_btn.setText("VENDER BOLETO");
        jPanel1.add(venderBoleto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 440, 80));

        idAccesoTxtField.setBackground(new java.awt.Color(236, 145, 117));
        idAccesoTxtField.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        idAccesoTxtField.setToolTipText("ID Acceso");
        jPanel1.add(idAccesoTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 430, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciar_sesion.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 250, 250));

        registrarseBtn.setBackground(new java.awt.Color(236, 145, 117));
        registrarseBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        registrarseBtn.setText("REGISTRARSE");
        registrarseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registrarseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 200, -1));

        salirBtn.setBackground(new java.awt.Color(236, 145, 117));
        salirBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        salirBtn.setText("SALIR");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        jPanel1.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 620, 110, -1));

        contraseñaTxt.setBackground(new java.awt.Color(236, 145, 117));
        contraseñaTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel1.add(contraseñaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 430, 60));

        iniciarSesionBtn1.setBackground(new java.awt.Color(236, 145, 117));
        iniciarSesionBtn1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        iniciarSesionBtn1.setText("INICIAR SESIÓN");
        iniciarSesionBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarSesionBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 620, -1, -1));

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel2.setText("ID ACCESO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel3.setText("CONTRASEÑA:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));

        cambiarContraseñaBtn1.setBackground(new java.awt.Color(236, 145, 117));
        cambiarContraseñaBtn1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        cambiarContraseñaBtn1.setText("CAMBIAR CONTRASEÑA");
        cambiarContraseñaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContraseñaBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarContraseñaBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void registrarseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseBtnActionPerformed
        VentanaRegistro registro = new VentanaRegistro();
        registro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarseBtnActionPerformed

    private void iniciarSesionBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionBtn1ActionPerformed
        Acceso acceso = new Acceso();
         
        String pass = new String(contraseñaTxt.getPassword());
  
        if(!idAccesoTxtField.getText().equals("") && !pass.equals("")){
            acceso.setCodigoAcceso(idAccesoTxtField.getText());
            acceso.setContraseñaAcceso(pass);
            if(acceso.iniciarSesion(acceso)){
                if(acceso.getCodigoAcceso().equals("ADMIN")){
                    VentanaAdministrador admin = new VentanaAdministrador();
                    admin.setVisible(true);
                    this.setVisible(false);
                }else{
                    VentanaVenderBoletos ventanaBoletos = new VentanaVenderBoletos();
                    ventanaBoletos.setVisible(true);
                    this.setVisible(false);
                }
            }else{
                JOptionPane.showMessageDialog(this, "El ID o la contraseña son incorrectas", "Datos incorrectos", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID y una contraseña para iniciar sesión", "Campo vacío", JOptionPane.WARNING_MESSAGE);
        }      
    }//GEN-LAST:event_iniciarSesionBtn1ActionPerformed

    private void cambiarContraseñaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContraseñaBtn1ActionPerformed
        VentanaCambiarContraseña cambiarContraseña = new VentanaCambiarContraseña();
        cambiarContraseña.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cambiarContraseñaBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarContraseñaBtn1;
    private javax.swing.JToggleButton consultarVentas_btn;
    private javax.swing.JPasswordField contraseñaTxt;
    private javax.swing.JTextField idAccesoTxtField;
    private javax.swing.JButton iniciarSesionBtn1;
    private javax.swing.JToggleButton iniciarSesion_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrarseBtn;
    private javax.swing.JButton salirBtn;
    private javax.swing.JToggleButton venderBoleto_btn;
    // End of variables declaration//GEN-END:variables
}

