package vistas;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Acceso;
import modelo.Administrador;
import modelo.Asiento;
import modelo.Autobus;

public class VentanaModificarDatosAutobus extends javax.swing.JFrame {

    public VentanaModificarDatosAutobus(Autobus datos) {      
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAPP.png")).getImage());
        setLocationRelativeTo(null);
        String numeroAutobus = String.valueOf(datos.getNumeroAutobus());
        numeroTxt.setText(numeroAutobus);
        origenTxt.setText(datos.getNombreOrigen());
        destinoTxt.setText(datos.getNombreDestino());
        String precio = String.valueOf(datos.getPrecioViaje());
        precioTxt.setText(precio);        
        fechaActualTxt.setText(datos.getFechaViaje());
        horarioTxt.setText(datos.getHorarioViaje());    
        altaBtn.setEnabled(false);
        consultarVentas_btn.setEnabled(false);
        cerrarSesion_btn.setEnabled(false);        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        consultarVentas_btn = new javax.swing.JToggleButton();
        cerrarSesion_btn = new javax.swing.JToggleButton();
        altaBtn = new javax.swing.JToggleButton();
        numeroLabel = new javax.swing.JLabel();
        numeroTxt = new javax.swing.JTextField();
        origenLabel = new javax.swing.JLabel();
        origenTxt = new javax.swing.JTextField();
        destinoLabel = new javax.swing.JLabel();
        fechaActualTxt = new javax.swing.JTextField();
        precioLabel = new javax.swing.JLabel();
        precioTxt = new javax.swing.JTextField();
        fechaLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        regresarBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        horarioTxt = new javax.swing.JFormattedTextField();
        fechaTxt = new com.toedter.calendar.JDateChooser();
        destinoTxt = new javax.swing.JTextField();
        fechaLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");

        jPanel5.setBackground(new java.awt.Color(242, 235, 244));
        jPanel5.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("LOGO");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        consultarVentas_btn.setBackground(new java.awt.Color(236, 145, 117));
        consultarVentas_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        consultarVentas_btn.setText("CONSULTAR VENTAS");
        jPanel5.add(consultarVentas_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 420, 80));

        cerrarSesion_btn.setBackground(new java.awt.Color(236, 145, 117));
        cerrarSesion_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        cerrarSesion_btn.setText("CERRAR SESIÓN");
        cerrarSesion_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesion_btnActionPerformed(evt);
            }
        });
        jPanel5.add(cerrarSesion_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 80));

        altaBtn.setBackground(new java.awt.Color(236, 145, 117));
        altaBtn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        altaBtn.setText("DAR DE ALTA A PERSONAL");
        altaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaBtnActionPerformed(evt);
            }
        });
        jPanel5.add(altaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 440, 80));

        numeroLabel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        numeroLabel.setText("NÚMERO DE AUTOBUS:");
        jPanel5.add(numeroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        numeroTxt.setEditable(false);
        numeroTxt.setBackground(new java.awt.Color(236, 145, 117));
        numeroTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel5.add(numeroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 260, 50));

        origenLabel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        origenLabel.setText("ORIGEN:");
        jPanel5.add(origenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        origenTxt.setBackground(new java.awt.Color(236, 145, 117));
        origenTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel5.add(origenTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 260, 50));

        destinoLabel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        destinoLabel.setText("DESTINO:");
        jPanel5.add(destinoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        fechaActualTxt.setBackground(new java.awt.Color(236, 145, 117));
        fechaActualTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel5.add(fechaActualTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 260, 50));

        precioLabel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        precioLabel.setText("PRECIO:");
        jPanel5.add(precioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, -1, -1));

        precioTxt.setBackground(new java.awt.Color(236, 145, 117));
        precioTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel5.add(precioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 260, 50));

        fechaLabel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        fechaLabel.setText("MODIFICAR FECHA:");
        jPanel5.add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        horarioLabel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        horarioLabel.setText("HORARIO:");
        jPanel5.add(horarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, -1, -1));

        regresarBtn.setBackground(new java.awt.Color(236, 145, 117));
        regresarBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        regresarBtn.setText("REGRESAR");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        jPanel5.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 660, 110, -1));

        modificarBtn.setBackground(new java.awt.Color(236, 145, 117));
        modificarBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        modificarBtn.setText("MODIFICAR");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });
        jPanel5.add(modificarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 110, -1));

        horarioTxt.setBackground(new java.awt.Color(236, 145, 117));
        try {
            horarioTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        horarioTxt.setToolTipText("00:00");
        jPanel5.add(horarioTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 100, 40));

        fechaTxt.setBackground(new java.awt.Color(236, 145, 117));
        fechaTxt.setDateFormatString("dd-MM-yyyy");
        fechaTxt.setDoubleBuffered(false);
        jPanel5.add(fechaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 260, 40));

        destinoTxt.setBackground(new java.awt.Color(236, 145, 117));
        destinoTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel5.add(destinoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 260, 50));

        fechaLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        fechaLabel1.setText("FECHA ACTUAL:");
        jPanel5.add(fechaLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesion_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesion_btnActionPerformed
        Acceso acceso = new Acceso();
        if(acceso.cerrarSesion()){
            VentanaLogin ventanaLogin = new VentanaLogin();
            ventanaLogin.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cerrarSesion_btnActionPerformed

    private void altaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBtnActionPerformed
        VentanaAltaPersonal alta = new VentanaAltaPersonal();
        alta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_altaBtnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        VentanaModificarAutobus menu = new VentanaModificarAutobus();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        Autobus autobus = new Autobus();
        Administrador admin = new Administrador();
        Asiento asiento = new Asiento();
        
        int numeroAutobus = Integer.parseInt(numeroTxt.getText());
        autobus.setNumeroAutobus(numeroAutobus);
        autobus.setNombreOrigen(origenTxt.getText());
        autobus.setNombreDestino(destinoTxt.getText());
        double precioViaje = Double.parseDouble(precioTxt.getText());
        autobus.setPrecioViaje(precioViaje);        
        try{
            SimpleDateFormat conv;
            conv = new SimpleDateFormat("yyyy-MM-dd");
            String fecha = conv.format(this.fechaTxt.getDate());
            autobus.setFechaViaje(fecha);
            if(validarHora(horarioTxt.getText())){
                autobus.setHorarioViaje(horarioTxt.getText() + ":00");                                     
                if(admin.modificarAutobus(autobus)){                   
                    JOptionPane.showMessageDialog(this, "Datos modificados correctamente", "Autobus actualizado", JOptionPane.INFORMATION_MESSAGE);                    
                }else{
                    JOptionPane.showMessageDialog(this, "Hubo un error al modificar el autobus, verifique los datos y vuelva a intentarlo", "Error al modificar", JOptionPane.ERROR_MESSAGE);
                }                    
            }else{
                JOptionPane.showMessageDialog(this, "La hora es incorrecta", "Error en la hora", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            autobus.setFechaViaje(fechaActualTxt.getText());
            if(validarHora(horarioTxt.getText())){
                autobus.setHorarioViaje(horarioTxt.getText() + ":00");                                     
                if(admin.modificarAutobus(autobus)){                   
                    JOptionPane.showMessageDialog(this, "Datos modificados correctamente", "Autobus actualizado", JOptionPane.INFORMATION_MESSAGE);                    
                }else{
                    JOptionPane.showMessageDialog(this, "Hubo un error al modificar el autobus, verifique los datos y vuelva a intentarlo", "Error al modificar", JOptionPane.ERROR_MESSAGE);
                }                    
            }else{
                JOptionPane.showMessageDialog(this, "La hora es incorrecta", "Error en la hora", JOptionPane.ERROR_MESSAGE);
            }
        }            
    }//GEN-LAST:event_modificarBtnActionPerformed

    public boolean validarHora(String hora) {
        boolean b;
        char[] a = hora.toString().toCharArray();
        String[] c = hora.split(":");
        if ((a[0] == ' ') || (a[1] == ' ') || (a[2] == ' ') || (a[3] == ' ') || (a[4] == ' ') || (getInteger(c[0]) > 24) || (getInteger(c[1]) > 59)) {
            b=false;
        }else{
            b=true;
        }
        return b;
    }
    
    public int getInteger(String valor){
        int integer = Integer.parseInt(valor);
        return integer;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarDatosAutobus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarDatosAutobus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarDatosAutobus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarDatosAutobus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaEditarDatosAutobus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton altaBtn;
    private javax.swing.JToggleButton cerrarSesion_btn;
    private javax.swing.JToggleButton consultarVentas_btn;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JTextField destinoTxt;
    private javax.swing.JTextField fechaActualTxt;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel fechaLabel1;
    private com.toedter.calendar.JDateChooser fechaTxt;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JFormattedTextField horarioTxt;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField numeroTxt;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JTextField origenTxt;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JTextField precioTxt;
    private javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables
}
