package vistas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Acceso;
import modelo.Administrador;
import modelo.Descuento;

public class VentanaAgregarDescuento extends javax.swing.JFrame {

    public VentanaAgregarDescuento() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAPP.png")).getImage());
        setLocationRelativeTo(null);
        altaBtn.setEnabled(false);
        consultarVentas_btn.setEnabled(false);
        cerrarSesion_btn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        consultarVentas_btn = new javax.swing.JToggleButton();
        cerrarSesion_btn = new javax.swing.JToggleButton();
        altaBtn = new javax.swing.JToggleButton();
        tipoDescuentoLabel = new javax.swing.JLabel();
        porcentajeDescuentoTxt = new javax.swing.JTextField();
        porcentajeLabel = new javax.swing.JLabel();
        cancelarBtn = new javax.swing.JButton();
        agregarBtn = new javax.swing.JButton();
        tipoDescuentoTxt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");

        jPanel5.setBackground(new java.awt.Color(242, 235, 244));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("LOGO");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        consultarVentas_btn.setBackground(new java.awt.Color(236, 145, 117));
        consultarVentas_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        consultarVentas_btn.setText("CONSULTAR VENTAS");
        consultarVentas_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVentas_btnActionPerformed(evt);
            }
        });
        jPanel5.add(consultarVentas_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 420, 80));

        cerrarSesion_btn.setBackground(new java.awt.Color(236, 145, 117));
        cerrarSesion_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        cerrarSesion_btn.setText("CERRAR SESIÓN");
        cerrarSesion_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesion_btnActionPerformed(evt);
            }
        });
        jPanel5.add(cerrarSesion_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 420, 80));

        altaBtn.setBackground(new java.awt.Color(236, 145, 117));
        altaBtn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        altaBtn.setText("DAR DE ALTA A PERSONAL");
        altaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaBtnActionPerformed(evt);
            }
        });
        jPanel5.add(altaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 440, 80));

        tipoDescuentoLabel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        tipoDescuentoLabel.setText("TIPO DE DESCUENTO:");
        jPanel5.add(tipoDescuentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        porcentajeDescuentoTxt.setBackground(new java.awt.Color(236, 145, 117));
        porcentajeDescuentoTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        porcentajeDescuentoTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel5.add(porcentajeDescuentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 200, 50));

        porcentajeLabel.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        porcentajeLabel.setText("PORCENTAJE DE DESCUENTO:");
        jPanel5.add(porcentajeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        cancelarBtn.setBackground(new java.awt.Color(236, 145, 117));
        cancelarBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        cancelarBtn.setText("REGRESAR");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        jPanel5.add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, 110, -1));

        agregarBtn.setBackground(new java.awt.Color(236, 145, 117));
        agregarBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        agregarBtn.setText("AGREGAR");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });
        jPanel5.add(agregarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 110, -1));

        tipoDescuentoTxt1.setBackground(new java.awt.Color(236, 145, 117));
        tipoDescuentoTxt1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel5.add(tipoDescuentoTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 240, 50));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setText("%");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 424, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesion_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesion_btnActionPerformed
        Acceso acceso = new Acceso();
        if(acceso.cerrarSesion()){
            VentanaLogin ventanaLogin = new VentanaLogin();
            ventanaLogin.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_cerrarSesion_btnActionPerformed

    private void altaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaBtnActionPerformed
        VentanaAltaPersonal alta = new VentanaAltaPersonal();
        alta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_altaBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        VentanaAdministrador menu = new VentanaAdministrador();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        Administrador admin = new Administrador();
        if(porcentajeDescuentoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un tipo de descuento", "Campo vacío", JOptionPane.WARNING_MESSAGE);            
        }else if(porcentajeDescuentoTxt.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un porcentaje de descuento", "Campo vacío", JOptionPane.WARNING_MESSAGE);            
        }else{
            Descuento descuento = new Descuento();
            descuento.setTipoDescuento(tipoDescuentoTxt1.getText());
            int porcentaje = Integer.parseInt(porcentajeDescuentoTxt.getText());
            descuento.setPorcentajeDescuento(porcentaje);
            if(admin.agregarDescuento(descuento)){
               JOptionPane.showMessageDialog(this, "El descuento se ha guardado con éxito", "Descuento guardado", JOptionPane.INFORMATION_MESSAGE);   
               tipoDescuentoTxt1.setText("");
               porcentajeDescuentoTxt.setText("");
            }else{
               JOptionPane.showMessageDialog(this, "No se ha podido agregar el descuento, intente nuevamente", "Error de datos", JOptionPane.ERROR_MESSAGE);            
            }            
        }        
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void consultarVentas_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVentas_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarVentas_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarDescuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarDescuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarDescuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAgregarDescuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAgregarDescuento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JToggleButton altaBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JToggleButton cerrarSesion_btn;
    private javax.swing.JToggleButton consultarVentas_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField porcentajeDescuentoTxt;
    private javax.swing.JLabel porcentajeLabel;
    private javax.swing.JLabel tipoDescuentoLabel;
    private javax.swing.JTextField tipoDescuentoTxt1;
    // End of variables declaration//GEN-END:variables
}
