package vistas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Acceso;

public class VentanaCambiarContraseña extends javax.swing.JFrame {
    Acceso acceso = new Acceso();
    
    public VentanaCambiarContraseña() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAPP.png")).getImage());
        setLocationRelativeTo(null);
        venderBoleto_btn.setEnabled(false);
        consultarVentas_btn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        consultarVentas_btn = new javax.swing.JToggleButton();
        iniciarSesion_Label = new javax.swing.JToggleButton();
        venderBoleto_btn = new javax.swing.JToggleButton();
        idAccesoTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cambiarContraseñaBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        contraseñaTxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contraseñaNuevaTxt = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");

        jPanel1.setBackground(new java.awt.Color(242, 235, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("LOGO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        consultarVentas_btn.setBackground(new java.awt.Color(236, 145, 117));
        consultarVentas_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        consultarVentas_btn.setText("CONSULTAR VENTAS");
        consultarVentas_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVentas_btnActionPerformed(evt);
            }
        });
        jPanel1.add(consultarVentas_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 420, 80));

        iniciarSesion_Label.setBackground(new java.awt.Color(236, 145, 117));
        iniciarSesion_Label.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        iniciarSesion_Label.setText("INICIAR SESIÓN");
        jPanel1.add(iniciarSesion_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 80));

        venderBoleto_btn.setBackground(new java.awt.Color(236, 145, 117));
        venderBoleto_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        venderBoleto_btn.setText("VENDER BOLETO");
        jPanel1.add(venderBoleto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 440, 80));

        idAccesoTxtField.setBackground(new java.awt.Color(236, 145, 117));
        idAccesoTxtField.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        idAccesoTxtField.setToolTipText("ID Acceso");
        jPanel1.add(idAccesoTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 430, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iniciar_sesion.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        cambiarContraseñaBtn.setBackground(new java.awt.Color(236, 145, 117));
        cambiarContraseñaBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        cambiarContraseñaBtn.setText("CAMBIAR CONTRASEÑA");
        cambiarContraseñaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContraseñaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cambiarContraseñaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, -1, -1));

        cancelarBtn.setBackground(new java.awt.Color(236, 145, 117));
        cancelarBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        cancelarBtn.setText("CANCELAR");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, 110, -1));

        contraseñaTxt.setBackground(new java.awt.Color(236, 145, 117));
        contraseñaTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel1.add(contraseñaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 430, 60));

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel2.setText("CONTRASEÑA ACTUAL:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel3.setText("ID DE EMPLEADO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        contraseñaNuevaTxt.setBackground(new java.awt.Color(236, 145, 117));
        contraseñaNuevaTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jPanel1.add(contraseñaNuevaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 430, 60));

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel5.setText("NUEVA CONTRASEÑA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarContraseñaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContraseñaBtnActionPerformed
        Acceso acceso = new Acceso();
         
        String pass = new String(contraseñaTxt.getPassword());
  
        if(!idAccesoTxtField.getText().equals("") && !pass.equals("")){
            acceso.setCodigoAcceso(idAccesoTxtField.getText());
            acceso.setContraseñaAcceso(pass);
            if(acceso.iniciarSesion(acceso)){
                String newPass = new String(contraseñaNuevaTxt.getPassword());             
                if(newPass.length() > 7){
                    if(acceso.cambiarContraseña(acceso.getCodigoAcceso(), newPass) == 1){
                        VentanaLogin login = new VentanaLogin();
                        login.setVisible(true);
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(this, "La contraseña ha sido cambiada con éxito", "Contraseña cambiada", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(this, "La contraseña nueva es la misma", "Contraseña repetida", JOptionPane.WARNING_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "La contraseña debe tener una longitud minima de 8 dígitos", "Contraseña debil", JOptionPane.WARNING_MESSAGE);
                }    
            }else{
                JOptionPane.showMessageDialog(this, "El ID o la contraseña son incorrectas", "Datos incorrectos", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe ingresar los datos", "Campo vacío", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_cambiarContraseñaBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        VentanaLogin ventanaLogin = new VentanaLogin();
        ventanaLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void consultarVentas_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVentas_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarVentas_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCambiarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarContraseñaBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JToggleButton consultarVentas_btn;
    private javax.swing.JPasswordField contraseñaNuevaTxt;
    private javax.swing.JPasswordField contraseñaTxt;
    private javax.swing.JTextField idAccesoTxtField;
    private javax.swing.JToggleButton iniciarSesion_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton venderBoleto_btn;
    // End of variables declaration//GEN-END:variables
}
