package vistas;

import com.sun.jdi.connect.spi.Connection;
import java.awt.print.PrinterJob;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Asiento;
import modelo.Autobus;
import modelo.Boleto;
import modelo.Conexion;
import modelo.Descuento;
import modelo.Pasajero;
import sistemaventaboletos.SistemaVentaBoletos;


public class VentanaDatosBoleto extends javax.swing.JFrame implements Printable{
    public VentanaDatosBoleto(Pasajero pasajero, Boleto boleto, Autobus autobus, Descuento descuento, Asiento asiento) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAPP.png")).getImage());
        setLocationRelativeTo(null);

        //origen
        setOrigenLabel.setText(autobus.getNombreOrigen());
        //destino
        setDestinoLabel.setText(autobus.getNombreDestino());
        //fecha
        setFechaLabel.setText(autobus.getFechaViaje());
        //horario
        setHorarioLabel.setText(autobus.getHorarioViaje());
        //Asiento
        setAsientoLabel.setText(asiento.obtenerAsientos());
        String asientoS = String.valueOf(asiento.getNumeroAsiento());
        setAsientoLabel.setText(asientoS);
       
        //nombre
        setNombre.setText(pasajero.getNombrePasajero());
        //apellido
        setApellidoPaterno.setText(pasajero.getApellidoPaternoPasajero());
        //apellidoPatenro
        setApellidoMaterno.setText(pasajero.getApellidoMaternoPasajero());
        //Total Final        
        String total = String.valueOf(boleto.getPrecioFinal());
        setPrecioLabel.setText(total);
        //Numero de autobus
        String numeroAutobus = String.valueOf(autobus.getNumeroAutobus());
        setAutobus.setText(numeroAutobus);
        
        //Código boleto        
        consultarID();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imprimir = new javax.swing.JPanel();
        logoLabel1 = new javax.swing.JLabel();
        origenLabel = new javax.swing.JLabel();
        destinoLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        setAsientoLabel = new javax.swing.JLabel();
        setFechaLabel = new javax.swing.JLabel();
        setPrecioLabel = new javax.swing.JLabel();
        setDestinoLabel = new javax.swing.JLabel();
        setOrigenLabel = new javax.swing.JLabel();
        salirBtn = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        imprimirBtn = new javax.swing.JButton();
        setHorarioLabel = new javax.swing.JLabel();
        asientoLabel = new javax.swing.JLabel();
        apellidoPaternoLabel = new javax.swing.JLabel();
        ApellidoMaternoLabel1 = new javax.swing.JLabel();
        setApellidoMaterno = new javax.swing.JLabel();
        setApellidoPaterno = new javax.swing.JLabel();
        setNombre = new javax.swing.JLabel();
        idBoletoLabel = new javax.swing.JLabel();
        setIDBoleto = new javax.swing.JLabel();
        autobusLabel = new javax.swing.JLabel();
        setAutobus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");

        imprimir.setBackground(new java.awt.Color(242, 235, 244));
        imprimir.setMinimumSize(new java.awt.Dimension(1280, 720));
        imprimir.setPreferredSize(new java.awt.Dimension(1280, 720));
        imprimir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logoLabel1.setText("LOGO");
        imprimir.add(logoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        origenLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        origenLabel.setText("ORIGEN:");
        imprimir.add(origenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        destinoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        destinoLabel.setText("DESTINO:");
        imprimir.add(destinoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        precioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        precioLabel.setText("PRECIO:");
        imprimir.add(precioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        fechaLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        fechaLabel.setText("FECHA DE SALIDA:");
        imprimir.add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        horarioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        horarioLabel.setText("HORARIO:");
        imprimir.add(horarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        setAsientoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setAsientoLabel.setText("Ttx");
        imprimir.add(setAsientoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        setFechaLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setFechaLabel.setText("Ttx");
        imprimir.add(setFechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        setPrecioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setPrecioLabel.setText(".");
        imprimir.add(setPrecioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 70, -1));

        setDestinoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setDestinoLabel.setText("Ttx");
        imprimir.add(setDestinoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        setOrigenLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setOrigenLabel.setText("Ttx");
        imprimir.add(setOrigenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        salirBtn.setBackground(new java.awt.Color(236, 145, 117));
        salirBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        salirBtn.setText("SALIR");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        imprimir.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        nombreLabel.setText("NOMBRE (S):");
        imprimir.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        imprimirBtn.setBackground(new java.awt.Color(236, 145, 117));
        imprimirBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        imprimirBtn.setText("IMPRIMIR");
        imprimirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBtnActionPerformed(evt);
            }
        });
        imprimir.add(imprimirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, -1, -1));

        setHorarioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setHorarioLabel.setText("Ttx");
        imprimir.add(setHorarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        asientoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        asientoLabel.setText("ASIENTO (S):");
        imprimir.add(asientoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        apellidoPaternoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        apellidoPaternoLabel.setText("APELLIDO MATERNO:");
        imprimir.add(apellidoPaternoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        ApellidoMaternoLabel1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ApellidoMaternoLabel1.setText("APELLIDO PATERNO:");
        imprimir.add(ApellidoMaternoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        setApellidoMaterno.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setApellidoMaterno.setText("Ttx");
        imprimir.add(setApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        setApellidoPaterno.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setApellidoPaterno.setText("Ttx");
        imprimir.add(setApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        setNombre.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setNombre.setText("Ttx");
        imprimir.add(setNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        idBoletoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        idBoletoLabel.setText("CÓDIGO DE BOLETO:");
        imprimir.add(idBoletoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        setIDBoleto.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setIDBoleto.setText("Ttx");
        imprimir.add(setIDBoleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        autobusLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        autobusLabel.setText("N° DE AUTOBUS:");
        imprimir.add(autobusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        setAutobus.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setAutobus.setText("Ttx");
        imprimir.add(setAutobus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        VentanaVenderBoletos principio = new VentanaVenderBoletos();
        principio.setVisible(true);
        this.setVisible(false);       
    }//GEN-LAST:event_salirBtnActionPerformed

    private void imprimirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBtnActionPerformed
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(this);
        if(job.printDialog()){
            try {
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(VentanaDatosBoleto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "La impresión se canceló", "No se pudo imprimir", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_imprimirBtnActionPerformed
   
    public void consultarID(){      
        Conexion conn = new Conexion();
        java.sql.Connection reg = conn.conectar();  
        java.sql.Connection con = reg; 
         
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        int asiento = Integer.parseInt(setAsientoLabel.getText());
        int autobus = Integer.parseInt(setAutobus.getText());
        
        String sql = "SELECT * FROM boleto INNER JOIN autobus" +
                    " ON boleto.numeroAutobus = autobus.numeroAutobus" +
                    " WHERE boleto.estado       LIKE 'Vendido'" +
                    " AND autobus.nombreOrigen  LIKE '" + setOrigenLabel.getText()  + "'" +
                    " AND autobus.nombreDestino LIKE '" + setDestinoLabel.getText() + "'" +
                    " AND boleto.numeroAsiento  LIKE '" + asiento                   + "'" +
                    " AND boleto.numeroAutobus  LIKE '" + autobus                   + "'";
        
        try{
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            if(rs.next()){
                setIDBoleto.setText(rs.getString(1));
            }
            
        }catch(Exception e){
            System.out.println("Error en la consulta: " + e);
        }      
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDatosBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaDatosBoleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoMaternoLabel1;
    private javax.swing.JLabel apellidoPaternoLabel;
    private javax.swing.JLabel asientoLabel;
    private javax.swing.JLabel autobusLabel;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JLabel idBoletoLabel;
    private javax.swing.JPanel imprimir;
    private javax.swing.JButton imprimirBtn;
    private javax.swing.JLabel logoLabel1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JButton salirBtn;
    private javax.swing.JLabel setApellidoMaterno;
    private javax.swing.JLabel setApellidoPaterno;
    private javax.swing.JLabel setAsientoLabel;
    private javax.swing.JLabel setAutobus;
    private javax.swing.JLabel setDestinoLabel;
    private javax.swing.JLabel setFechaLabel;
    private javax.swing.JLabel setHorarioLabel;
    private javax.swing.JLabel setIDBoleto;
    private javax.swing.JLabel setNombre;
    private javax.swing.JLabel setOrigenLabel;
    private javax.swing.JLabel setPrecioLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if(pageIndex == 0){
            Graphics2D graphics2d = (Graphics2D) graphics;
            graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            printAll(graphics2d);
            return PAGE_EXISTS;
        }else{
            return NO_SUCH_PAGE;
        }
    }
}
