package vistas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Asiento;
import modelo.Autobus;
import modelo.Boleto;
import modelo.Descuento;
import modelo.Pasajero;

public class VentanaNuevoCobro extends javax.swing.JFrame {

    public VentanaNuevoCobro(Pasajero pasajero, Boleto boleto, Autobus autobus, Descuento descuento, Asiento asiento) {
        initComponents();   
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconoAPP.png")).getImage());
        setLocationRelativeTo(null);
        venderBoleto_btn.setEnabled(false);        
        cerrarSesionBtn.setEnabled(false);
        consultarVentas_btn.setEnabled(false);
        
        //NumeroAutobus
        String numAutobus = String.valueOf(autobus.getNumeroAutobus());
        numeroAutobusTxt.setText(numAutobus);
        //origen
        setOrigenLabel.setText(autobus.getNombreOrigen());
        //destino
        setDestinoLabel.setText(autobus.getNombreDestino());
        //precio
        String precio = String.valueOf(autobus.getPrecioViaje());
        setPrecioLabel.setText(precio);
        //fecha
        setFechaLabel.setText(autobus.getFechaViaje());
        //horario
        setHorarioLabel.setText(autobus.getHorarioViaje());
        //Asiento
        setAsientoLabel.setText(asiento.obtenerAsientos());
       
        //nombre
        setNombre.setText(pasajero.getNombrePasajero());
        //apellido
        setApellidoPaterno.setText(pasajero.getApellidoPaternoPasajero());
        //apellidoPatenro
        setApellidoMaterno.setText(pasajero.getApellidoMaternoPasajero());
        //descuento
        setDescuentoTxt.setText(descuento.getTipoDescuento());          
        //PrecioAnterior
        String precioAnterior = String.valueOf(boleto.getPrecioFinal());
        setPrecioAnterior.setText(precioAnterior);
        
        //Total Final        
        double precioNormal = Double.parseDouble(setPrecioLabel.getText());
        
        double descuentoD = 0.0;
        descuentoD = ((precioNormal * descuento.getPorcentajeDescuento()) / 100);
        String descuentoString = String.valueOf(descuentoD);
        setDescuento.setText(descuentoString);
        
        double precioDescuento = precioNormal - descuentoD;
        String precioDescuentoString = String.valueOf(precioDescuento);
        setPrecioDescuento.setText(precioDescuentoString);        
        
        double precioAnteriorDouble = Double.parseDouble(setPrecioAnterior.getText());
        if(precioAnteriorDouble < 0.0){
            precioAnteriorDouble = precioAnteriorDouble * -1;
        }
        
        double precioFinal = 0.0;
        precioFinal = precioDescuento - precioAnteriorDouble;        
        String precioString = String.valueOf(precioFinal);
        setTotalPagar.setText(precioString);                
        
        if(precioFinal <= 0){
            pagoTxt.setText(precioString);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logoLabel1 = new javax.swing.JLabel();
        cerrarSesionBtn = new javax.swing.JToggleButton();
        venderBoleto_btn = new javax.swing.JToggleButton();
        consultarVentas_btn = new javax.swing.JToggleButton();
        origenLabel = new javax.swing.JLabel();
        destinoLabel = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        horarioLabel = new javax.swing.JLabel();
        setAsientoLabel = new javax.swing.JLabel();
        setFechaLabel = new javax.swing.JLabel();
        setPrecioLabel = new javax.swing.JLabel();
        setDestinoLabel = new javax.swing.JLabel();
        setOrigenLabel = new javax.swing.JLabel();
        regresarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOculta = new javax.swing.JTable();
        nombreLabel = new javax.swing.JLabel();
        cobrarBtn = new javax.swing.JButton();
        setHorarioLabel = new javax.swing.JLabel();
        numeroAutobusTxt = new javax.swing.JLabel();
        pagoTxt = new javax.swing.JTextField();
        asientoLabel = new javax.swing.JLabel();
        apellidoPaternoLabel = new javax.swing.JLabel();
        cambioLabel = new javax.swing.JLabel();
        ApellidoMaternoLabel = new javax.swing.JLabel();
        seleccionarDescuento = new javax.swing.JLabel();
        setCambio = new javax.swing.JLabel();
        totalPagarLabel = new javax.swing.JLabel();
        pagoLabel = new javax.swing.JLabel();
        setTotalPagar = new javax.swing.JLabel();
        setApellidoMaterno = new javax.swing.JLabel();
        setApellidoPaterno = new javax.swing.JLabel();
        setNombre = new javax.swing.JLabel();
        setDescuentoTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        setDescuento = new javax.swing.JLabel();
        boletoCanceladoLabel = new javax.swing.JLabel();
        setPrecioAnterior = new javax.swing.JLabel();
        precioDescuentoLabel = new javax.swing.JLabel();
        setPrecioDescuento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Venta de Boletos");

        jPanel2.setBackground(new java.awt.Color(242, 235, 244));
        jPanel2.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logoLabel1.setText("LOGO");
        jPanel2.add(logoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        cerrarSesionBtn.setBackground(new java.awt.Color(236, 145, 117));
        cerrarSesionBtn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        cerrarSesionBtn.setText("CERRAR SESIÓN");
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cerrarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 420, 80));

        venderBoleto_btn.setBackground(new java.awt.Color(236, 145, 117));
        venderBoleto_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        venderBoleto_btn.setText("VENDER BOLETO");
        venderBoleto_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderBoleto_btnActionPerformed(evt);
            }
        });
        jPanel2.add(venderBoleto_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 440, 80));

        consultarVentas_btn.setBackground(new java.awt.Color(236, 145, 117));
        consultarVentas_btn.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        consultarVentas_btn.setText("CONSULTAR VENTAS");
        jPanel2.add(consultarVentas_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 420, 80));

        origenLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        origenLabel.setText("ORIGEN:");
        jPanel2.add(origenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        destinoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        destinoLabel.setText("DESTINO:");
        jPanel2.add(destinoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        precioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        precioLabel.setText("PRECIO NORMAL:");
        jPanel2.add(precioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        fechaLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        fechaLabel.setText("FECHA DE SALIDA:");
        jPanel2.add(fechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, -1, -1));

        horarioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        horarioLabel.setText("HORARIO:");
        jPanel2.add(horarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        setAsientoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setAsientoLabel.setText("Ttx");
        jPanel2.add(setAsientoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        setFechaLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setFechaLabel.setText("Ttx");
        jPanel2.add(setFechaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        setPrecioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setPrecioLabel.setText(".");
        jPanel2.add(setPrecioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 60, -1));

        setDestinoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setDestinoLabel.setText("Ttx");
        jPanel2.add(setDestinoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        setOrigenLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setOrigenLabel.setText("Ttx");
        jPanel2.add(setOrigenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        regresarBtn.setBackground(new java.awt.Color(236, 145, 117));
        regresarBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        regresarBtn.setText("REGRESAR");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(regresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, -1, -1));

        tablaOculta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaOculta.setEnabled(false);
        tablaOculta.setFocusable(false);
        jScrollPane1.setViewportView(tablaOculta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 20, 20));

        nombreLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        nombreLabel.setText("NOMBRE (S):");
        jPanel2.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, -1, -1));

        cobrarBtn.setBackground(new java.awt.Color(236, 145, 117));
        cobrarBtn.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        cobrarBtn.setText("COBRAR");
        cobrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrarBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cobrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 670, -1, -1));

        setHorarioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setHorarioLabel.setText("Ttx");
        jPanel2.add(setHorarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        numeroAutobusTxt.setText("jLabel7");
        jPanel2.add(numeroAutobusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 130, -1, -1));

        pagoTxt.setBackground(new java.awt.Color(236, 145, 117));
        pagoTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        pagoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pagoTxtKeyReleased(evt);
            }
        });
        jPanel2.add(pagoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, 70, 40));

        asientoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        asientoLabel.setText("ASIENTO (S):");
        jPanel2.add(asientoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        apellidoPaternoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        apellidoPaternoLabel.setText("APELLIDO MATERNO:");
        jPanel2.add(apellidoPaternoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        cambioLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        cambioLabel.setText("CAMBIO:");
        jPanel2.add(cambioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, -1, 40));

        ApellidoMaternoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ApellidoMaternoLabel.setText("APELLIDO PATERNO:");
        jPanel2.add(ApellidoMaternoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));

        seleccionarDescuento.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        seleccionarDescuento.setText("DESCUENTO:");
        jPanel2.add(seleccionarDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        setCambio.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setCambio.setText("0.0");
        jPanel2.add(setCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 240, 40));

        totalPagarLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        totalPagarLabel.setText("TOTAL A PAGAR:");
        jPanel2.add(totalPagarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, -1, 40));

        pagoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        pagoLabel.setText("PAGO: ");
        jPanel2.add(pagoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, 40));

        setTotalPagar.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setTotalPagar.setText(".");
        jPanel2.add(setTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 240, 40));

        setApellidoMaterno.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setApellidoMaterno.setText("Ttx");
        jPanel2.add(setApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, -1, -1));

        setApellidoPaterno.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setApellidoPaterno.setText("Ttx");
        jPanel2.add(setApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 250, -1, -1));

        setNombre.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setNombre.setText("Ttx");
        jPanel2.add(setNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, -1, -1));

        setDescuentoTxt.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setDescuentoTxt.setText(".");
        jPanel2.add(setDescuentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 160, -1));

        jLabel1.setText("________________________________________________________________________________");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 420, -1));

        setDescuento.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setDescuento.setText("00.00");
        jPanel2.add(setDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 100, -1));

        boletoCanceladoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        boletoCanceladoLabel.setText("BOLETO CANCELADO:");
        jPanel2.add(boletoCanceladoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, -1, 40));

        setPrecioAnterior.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setPrecioAnterior.setText(".");
        jPanel2.add(setPrecioAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 240, 40));

        precioDescuentoLabel.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        precioDescuentoLabel.setText("PRECIO CON DESCUENTO:");
        jPanel2.add(precioDescuentoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        setPrecioDescuento.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        setPrecioDescuento.setText("00.00");
        jPanel2.add(setPrecioDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed

    }//GEN-LAST:event_cerrarSesionBtnActionPerformed

    private void venderBoleto_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderBoleto_btnActionPerformed

    }//GEN-LAST:event_venderBoleto_btnActionPerformed

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        Autobus autobus = new Autobus();
        Asiento asiento = new Asiento();
        Boleto boleto = new Boleto();

        int numeroAutobus = Integer.parseInt(numeroAutobusTxt.getText());
        autobus.setNumeroAutobus(numeroAutobus);
        //origen
        autobus.setNombreOrigen(setOrigenLabel.getText());
        //destino
        autobus.setNombreDestino(setDestinoLabel.getText());
        //Precio viaje
        double precio = Double.parseDouble(setPrecioLabel.getText());
        autobus.setPrecioViaje(precio);
        //fecha
        autobus.setFechaViaje(setFechaLabel.getText());
        //horario
        autobus.setHorarioViaje(setHorarioLabel.getText());
        //Asiento
        int asientoInt = Integer.parseInt(setAsientoLabel.getText());
        asiento.setNumeroAsiento(asientoInt);
        asiento.add(asiento);

        VentanaDatosPasajero ventanaDatos = new VentanaDatosPasajero(autobus, asiento, boleto);
        ventanaDatos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void cobrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrarBtnActionPerformed
        Autobus autobus = new Autobus();
        Pasajero pasajero = new Pasajero();
        Descuento descuento = new Descuento();
        Boleto boleto = new Boleto();
        Asiento asiento = new Asiento();
        Asiento arrayAsiento = new Asiento();

        if(pagoTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar el monto dado por el pasajero", "Monto no ingresado", JOptionPane.WARNING_MESSAGE);
        }else{
            //Numero autobus
            int numeroAutobus = Integer.parseInt(numeroAutobusTxt.getText());
            autobus.setNumeroAutobus(numeroAutobus);
            //origen
            autobus.setNombreOrigen(setOrigenLabel.getText());
            //destino
            autobus.setNombreDestino(setDestinoLabel.getText());
            //fecha
            autobus.setFechaViaje(setFechaLabel.getText());
            //horario
            autobus.setHorarioViaje(setHorarioLabel.getText());
            //nombre
            pasajero.setNombrePasajero(setNombre.getText());
            //apellidoMaterno
            pasajero.setApellidoPaternoPasajero(setApellidoPaterno.getText());
            //apellidoPaterno
            pasajero.setApellidoMaternoPasajero(setApellidoMaterno.getText());
            //Asiento
            int asientoInt = Integer.parseInt(setAsientoLabel.getText());
            boleto.setNumeroAsiento(asientoInt);
            //descuento
            descuento.setTipoDescuento(setDescuentoTxt.getText());
            //Total Final
            double precio = Double.parseDouble(setTotalPagar.getText());
            boleto.setPrecioFinal(precio);

            arrayAsiento.setNumeroAsiento(asientoInt);
            arrayAsiento.add(arrayAsiento);

            if(boleto.generarBoleto(pasajero, boleto, autobus, descuento)){
                asiento.setNumeroAutobus(numeroAutobus);
                asiento.setNumeroAsiento(asientoInt);
                asiento.setEstado(0);
                asiento.cambiarEstado(asiento);
                VentanaDatosBoleto boletoVendido = new VentanaDatosBoleto(pasajero, boleto, autobus, descuento, asiento);
                boletoVendido.setVisible(true);
                this.setVisible(false);

            }else{
                System.out.println("Falló algo :(");
            }
        }
    }//GEN-LAST:event_cobrarBtnActionPerformed

    private void pagoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagoTxtKeyReleased
        try{
            double pago = Double.parseDouble(pagoTxt.getText());
            double totalPagar = Double.parseDouble(setTotalPagar.getText());
            double cambio = 0.0;
            cambio = pago - totalPagar;
            String cambioS = String.valueOf(cambio);
            setCambio.setText(cambioS);
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_pagoTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaNuevoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaNuevoCobro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoMaternoLabel;
    private javax.swing.JLabel apellidoPaternoLabel;
    private javax.swing.JLabel asientoLabel;
    private javax.swing.JLabel boletoCanceladoLabel;
    private javax.swing.JLabel cambioLabel;
    private javax.swing.JToggleButton cerrarSesionBtn;
    private javax.swing.JButton cobrarBtn;
    private javax.swing.JToggleButton consultarVentas_btn;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel horarioLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel numeroAutobusTxt;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JLabel pagoLabel;
    private javax.swing.JTextField pagoTxt;
    private javax.swing.JLabel precioDescuentoLabel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JButton regresarBtn;
    private javax.swing.JLabel seleccionarDescuento;
    private javax.swing.JLabel setApellidoMaterno;
    private javax.swing.JLabel setApellidoPaterno;
    private javax.swing.JLabel setAsientoLabel;
    private javax.swing.JLabel setCambio;
    private javax.swing.JLabel setDescuento;
    private javax.swing.JLabel setDescuentoTxt;
    private javax.swing.JLabel setDestinoLabel;
    private javax.swing.JLabel setFechaLabel;
    private javax.swing.JLabel setHorarioLabel;
    private javax.swing.JLabel setNombre;
    private javax.swing.JLabel setOrigenLabel;
    private javax.swing.JLabel setPrecioAnterior;
    private javax.swing.JLabel setPrecioDescuento;
    private javax.swing.JLabel setPrecioLabel;
    private javax.swing.JLabel setTotalPagar;
    private javax.swing.JTable tablaOculta;
    private javax.swing.JLabel totalPagarLabel;
    private javax.swing.JToggleButton venderBoleto_btn;
    // End of variables declaration//GEN-END:variables
}
